config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

before_action :set_dose, only: [:show, :edit, :update, :destroy]
before_action :set_cocktail, only: [:new, :create]

  def new
   @ingredients = Ingredient.all
   @dose = Dose.new
  end

  def create
   @dose = Dose.new(dose_params)
   @dose.cocktail = @cocktail
   if @dose.save
   redirect_to cocktail_path(@cocktail)
   else
     render :new
   end
  end

  def destroy
   @cocktail = @dose.cocktail
   @dose.destroy

   redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
   @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
   @dose = Dose.find(params[:id])
  end

  def dose_params
   params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>

  <%= f.input :name, label: "name" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
<% end %>
<h3><%= link_to 'Back', cocktails_path(@cocktails) %></h3>

app/views/cocktails/edit.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://assets.afcdn.com/recipe/20180705/80288_w648h344c1cx1473cy1313cxt0cyt0cxb4493cyb3286.jpg);">
  <div>
    <h1>Welcome to the Mixoteque</h1>
    <%= link_to "Add a new Cocktail", new_cocktail_path(@cocktails), class:"btn btn-ghost" %>
  </div>
</div>
<div class="card-container">
  <% @cocktails.each do |cocktail| %>
    <div class="card-product">
      <img src="https://source.unsplash.com/featured/?cocktail">
      <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
      <p><%= link_to 'Delete', cocktail_path(cocktail),method: :delete, data: { confirm: "Delete this cocktail from the Mixoteque ?" } %></p>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<h3><%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail) %></h3>
<h3><% link_to 'Back', cocktails_path %></h3

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
     <%= f.input :description %>
     <%= f.association :ingredient  %>
   <%= f.button :submit %>
 <% end %>

<%= link_to “Back”, cocktail_path(@cocktail) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>